function [icpEstimate,alignedDataOut]= icpNose(template,data,templatePrnLocation)

addpath('toolboxes\icp\');
% Read in template image and store nose tip

q = template';
p = data';

% USE ICP
[TR, TT] = icp(q,p,'Matching','kDtree');

% Align model using parameters generated by icp
alignedData = TR*p + repmat(TT,1,length(p));

%find loction on surface of alignedDataImage which is closest to prn of
%model.
k_nearest = dsearchn(alignedData(1:2,:)',templatePrnLocation(1:end));
alignedDataOut = alignedData';

icpEstimate = alignedData(1:2,k_nearest);